// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoenixCust.CodeFirstEntities;

namespace PhoenixCust.Migrations
{
    [DbContext(typeof(CodeFirstContext))]
    [Migration("20210325004720_testdata")]
    partial class testdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhoenixCust.CodeFirstEntities.CodeFirstCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Busname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custcellphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custemailaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeFirstCustomers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Busname = "Applacres,Inc.",
                            Custcellphone = "812-279-9721",
                            Custemailaddress = "applacresinc@gmail.com",
                            Custname = "Dave Byers",
                            Password = "spring123"
                        });
                });

            modelBuilder.Entity("PhoenixCust.CodeFirstEntities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            ProjectName = "applacres.net",
                            Status = "quarterly"
                        });
                });

            modelBuilder.Entity("PhoenixCust.CodeFirstEntities.Project", b =>
                {
                    b.HasOne("PhoenixCust.CodeFirstEntities.CodeFirstCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
